# Generated by Django 5.2.7 on 2025-10-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosiniciais',
            name='genero',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
