# Generated by Django 5.2.7 on 2025-10-15 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dadosiniciais_genero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesoes_anteriores', models.TextField(blank=True, help_text='Descreva lesões, dores, cirurgias, problemas ortopédicos, etc.', null=True)),
                ('doencas_cronicas', models.TextField(blank=True, help_text='Hipertensão, diabetes, problemas cardíacos, pulmonares, etc.', null=True)),
                ('medicamentos', models.TextField(blank=True, help_text='Liste medicamentos em uso e seus efeitos.', null=True)),
                ('alergias', models.TextField(blank=True, help_text='Alerta sobre alergias conhecidas.', null=True)),
                ('restricoes_medicas', models.TextField(blank=True, help_text='Qualquer restrição ou recomendação médica.', null=True)),
                ('atividade_fisica_atual', models.TextField(blank=True, help_text='Descreva sua prática atual de exercícios.', null=True)),
                ('horas_sono_noite', models.PositiveIntegerField(blank=True, null=True)),
                ('fumante', models.BooleanField(default=False)),
                ('cigarros_dia', models.PositiveIntegerField(blank=True, null=True)),
                ('consumo_alcool', models.TextField(blank=True, null=True)),
                ('alimentacao', models.TextField(blank=True, help_text='Refeições por dia, consumo de água, suplementação.', null=True)),
                ('objetivos', models.TextField(help_text='Quais são seus principais objetivos com o treino?')),
                ('preferencias_exercicios', models.TextField(blank=True, help_text='Gosta ou não gosta de alguns exercícios?', null=True)),
                ('declaracao_verdade', models.BooleanField(default=False, help_text='Declaro que as informações prestadas são verdadeiras.')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
