# Generated by Django 5.2.7 on 2025-10-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_anamnese'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosiniciais',
            name='celular',
            field=models.CharField(blank=True),
        ),
    ]
