# Generated by Django 5.2.7 on 2025-12-09 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dadosiniciais_celular'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='preCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('celular', models.CharField(max_length=255)),
                ('peso', models.FloatField(blank=True)),
                ('altura', models.IntegerField(blank=True)),
                ('objetivo', models.CharField(max_length=255)),
                ('frequencia', models.CharField(max_length=255)),
                ('nivel', models.CharField(max_length=255)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
