# Generated by Django 5.2.7 on 2025-12-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_precadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precadastro',
            name='personal',
            field=models.IntegerField(blank=True),
        ),
    ]
