# Generated by Django 5.2.7 on 2025-12-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_precadastro_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precadastro',
            name='altura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='precadastro',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='precadastro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='precadastro',
            name='personal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='precadastro',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
