# Generated by Django 5.2.7 on 2025-12-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_precadastro_altura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precadastro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
