# Generated by Django 5.2.7 on 2025-12-15 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_precadastro_created_at'),
        ('app_personal', '0007_alter_exercicioscliente_microciclo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('torax', models.FloatField(null=True)),
                ('cintura', models.FloatField(null=True)),
                ('quadril', models.FloatField(null=True)),
                ('braco_direito', models.FloatField(null=True)),
                ('braco_esquerdo', models.FloatField(null=True)),
                ('coxa_direita', models.FloatField(null=True)),
                ('coxa_esquerda', models.FloatField(null=True)),
                ('mesociclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesociclo', to='app_personal.mesociclo')),
            ],
        ),
    ]
