# Generated by Django 5.2.7 on 2025-12-16 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_medidas'),
        ('app_personal', '0007_alter_exercicioscliente_microciclo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidas',
            name='mesociclo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesociclo', to='app_personal.mesociclo'),
        ),
    ]
