# Generated by Django 5.2.7 on 2025-12-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_medidas_user'),
        ('app_personal', '0007_alter_exercicioscliente_microciclo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidas',
            name='mesociclo',
        ),
        migrations.AddField(
            model_name='medidas',
            name='mesociclo',
            field=models.ManyToManyField(null=True, related_name='mesociclo', to='app_personal.mesociclo'),
        ),
    ]
