# Generated by Django 5.2.7 on 2025-12-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_medidas_mesociclo_medidas_mesociclo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidas',
            name='mesociclo',
        ),
        migrations.AddField(
            model_name='medidas',
            name='mesociclo_id',
            field=models.IntegerField(null=True),
        ),
    ]
