# Generated by Django 5.2.7 on 2025-12-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_medidas_mesociclo_medidas_mesociclo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidas',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
