# Generated by Django 5.2.7 on 2026-01-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_medidas_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidas',
            name='pescoco',
            field=models.FloatField(null=True),
        ),
    ]
