# Generated by Django 5.2.7 on 2025-10-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaexercicios',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
