# Generated by Django 5.2.7 on 2025-10-07 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_personal', '0002_categoriaexercicios_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_personal.categoriaexercicios')),
            ],
        ),
    ]
