# Generated by Django 5.2.7 on 2025-10-09 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_personal', '0004_mesociclo_microciclo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciciosCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=255)),
                ('reps', models.CharField(max_length=255)),
                ('obs', models.CharField(max_length=255)),
                ('conjugado', models.IntegerField(null=True)),
                ('microciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_personal.microciclo')),
            ],
        ),
    ]
