# Generated by Django 5.2.7 on 2025-10-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_personal', '0005_exercicioscliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicioscliente',
            name='url_img',
            field=models.TextField(blank=True),
        ),
    ]
