# Generated by Django 5.2.7 on 2025-12-09 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_personal', '0006_exercicioscliente_url_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicioscliente',
            name='microciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='app_personal.microciclo'),
        ),
        migrations.AlterField(
            model_name='microciclo',
            name='mesociclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microciclo', to='app_personal.mesociclo'),
        ),
    ]
